- name: Deploy stack unit
  become: true
  template:
    src: files/stack.service
    dest: /lib/systemd/system/stack.service

- name: Deploy stack script
  become: true
  become_user: stack
  template:
    src: files/stack_service.sh
    dest: "{{ BASE }}/workshop/stack_service.sh"

- name: Enable the stack service
  become: true
  command: systemctl enable stack

- name: Touch a .clean file to mark the image as new
  become: true
  become_user: stack
  command: >
    touch "{{ BASE }}/workshop/.clean"
  args:
    creates: "{{ BASE }}/workshop/.clean"
