---
- hosts: cloud
  gather_facts: yes
  vars_files:
    - devstack_gate_vars.yaml
  roles:
    - gather_host_info
    - fix_etc_hosts
    - fix_disk_layout
    - create_base_folder
    - start_fresh_logging
    - setup_stack_user
    - setup_tempest_user
