---
- hosts: localhost
  tasks:
    - name: Setup a VM to create the workshop image
      os_server:
       state: present
       cloud: "{{ cloud_profile }}"
       name: workshop_base
       image: "Ubuntu 16.04"
       key_name: "{{ cloud_keyname }}"
       timeout: 200
       flavor: r2-15
      register: vm
    - name: Add the VM to the inventory
      add_host:
        name: "{{ vm.openstack.interface_ip }}"
        group: cloud

- hosts: cloud
  gather_facts: yes
  roles:
    - initial_setup
    - gather_host_info
    - fix_etc_hosts
    - fix_disk_layout
    - create_base_folder
    - start_fresh_logging
    - stack_user
    - setup_tempest_user
    - pre_install_devstack_stuff
    - configure_devstack
