- name: Create the workshop folder
  become: true
  file:
    path: "{{ BASE }}/workshop"
    state: directory
    mode: 0755
    owner: stack

- name: Clone all workshop git repos from github
  become: true
  become_user: stack
  git:
    repo: "https://github.com/{{ item }}"
    dest: "{{ BASE }}/workshop/{{ item | basename }}"
  with_items:
  - afrittoli/cross_service_tempest_plugins
  - afrittoli/designate-tempest-plugin
  - afrittoli/heat-tempest-plugin
  - openstack/tempest-plugin-cookiecutter

- name: Touch a .clean file to mark the image as new
  file:
    path: "{{ BASE }}/workshop/.clean"
    state: touch
